apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-sts
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ServiceExpose
            metadata:
              name: example-service-trait
            spec:
              template:
                ports:
                  - port: 80
                    name: nginx
                    targetPort: 80
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: IngressTrait
            metadata:
              name: example-ingress-trait
            spec:
              template:
                rules:
                  - host: nginx.oam.com
                    http:
                      paths:
                        - path: /
                          backend:
                            serviceName: test
                            servicePort: 80