name: grafana
version: v0.4.0
description: Grafana is a multi-platform open source analytics and interactive visualization web application. It provides charts, graphs, and alerts for the web when connected to supported data sources.
icon: https://artifacthub.io/image/e69a4034-cfe7-4fa8-95ce-df3837f5d717@1x
url: https://grafana.com/

tags:
 - Observability
 - Kubernetes
 - Grafana

invisible: false

dependencies:
 - name: o11y-definitions

system:
  vela: ">=v1.7.0"
