apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig-rollout
spec:
  components:
    - componentName: example-component
      traits:
        - trait:
            apiVersion: extend.oam.dev/v1alpha2
            kind: SimpleRolloutTrait
            metadata:
              # TODO(negz): This name can be omitted and generated automatically if
              # each trait kind may apply only once to a component/workload.
              name:  example-rollout-trait
              # name: example-rollout-trait-deployment # test for .metadata.name duplicated
            spec:
              replica: 6
              maxUnavailable: 2
              batch: 2
