{{- if .Values.admissionWebhooks.enabled -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "metricstrait.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  {{- if .Values.admissionWebhooks.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "metricstrait.fullname" .) | quote }}
  {{- end }}
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: {{ template "metricstrait.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-standard-oam-dev-v1alpha1-metricstrait
    {{- if .Values.admissionWebhooks.patch.enabled  }}
    failurePolicy: Ignore
    {{- else }}
    failurePolicy: Fails
    {{- end }}
    name: mmetricstrait.kb.io
    rules:
      - apiGroups:
          - standard.oam.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - metricstraits

{{- end -}}